App\Entity\Location:
    properties:
        city:
            - NotBlank:
                  message: 'Podaj nazwę miasta.'
                  groups: [create]
            - Length:
                  min: 2
                  max: 60
                  minMessage: 'Miasto ma mieć min. {{ limit }} znaki.'
                  maxMessage: 'Miasto ma mieć maks. {{ limit }} znaków.'
                  groups: [create, edit]

        country:
            - Choice:
                  choices: [PL, DE, FR, ES, IT, GB, US]
                  message: 'Nieprawidłowy kraj.'
                  groups: [create, edit]

        latitude:
            - NotNull:
                  message: 'Podaj szerokość geograficzną.'
                  groups: [create]
            - Range:
                  min: -90
                  max: 90
                  notInRangeMessage: 'Szerokość musi być między {{ min }} a {{ max }}.'
                  groups: [create, edit]

        longitude:
            - NotNull:
                  message: 'Podaj długość geograficzną.'
                  groups: [create]
            - Range:
                  min: -180
                  max: 180
                  notInRangeMessage: 'Długość musi być między {{ min }} a {{ max }}.'
                  groups: [create, edit]
